#!/usr/bin/env python3
"""
inverse_design.py
Inverse design of ceramic tile compositions via three methods.
This module is a pure backend library imported by streamlit_app.py.
It contains no plotting or file-output logic.

METHODS
  1. Nearest Neighbour — non-optimised (property proximity only)
     Returns the single synthetic dataset sample whose predicted properties
     are closest to the target in scaled property space. Serves as a
     baseline — no cost or CO2 consideration.

  2. Nearest Neighbour — cost + CO2 optimised
     Searches the 10 nearest neighbours in scaled property space and
     selects the composition with the lowest combined cost + CO2 rank.

  3. Bayesian Optimisation (Optuna TPE)
     Searches the continuous composition space to minimise normalised
     cost + normalised CO2 subject to meeting the target properties.

     GUARDRAIL (added — fixes unrealistic / blown-up results):
     Each of the 7 free materials is sampled independently across its own
     bound box, then SodaF is derived and the whole vector renormalised to
     100 wt%. This can land on a composition that is individually in-bounds
     for every material yet jointly far outside the correlated region the
     synthetic generator actually explored (see generate_dataset.py: the
     simplex constraint Sigma wt% = 100 induces structural multicollinearity).
     Off that training manifold, a data-driven forward model — especially
     a linear one, whose near-cancelling coefficients only cancel ON the
     manifold — can extrapolate to physically nonsensical values (e.g.
     MOR in the billions). Two penalties now keep the optimiser (and the
     result it returns) inside the region the model was actually trained
     on:
       (a) a composition trust-region penalty: distance from the candidate
           to its nearest synthetic training point, in units of the
           typical training-point-to-training-point spacing;
       (b) a property sanity penalty: how far the model's own predicted
           MOR/WA/Shrinkage fall outside the observed training range
           (with a margin).
     Every trial is tagged "feasible" (both penalties ~0). The final
     answer is chosen from feasible trials only; if none exist, the least
     bad trial is returned WITH a warning rather than silently presented
     as a normal result.

ARCHITECTURE — PREDICTION vs. OPTIMISATION
-------------------------------------------------------
Two independent engines live in this framework:

  Engine 1 — Prediction (forward_model):
      Learns Composition -> Properties. This relationship does NOT depend
      on raw-material price. The model is NOT retrained when prices change.

  Engine 2 — Optimisation (Methods 1-3 below):
      Uses Composition + CURRENT price/CO2 tables to evaluate an objective
      (min cost, min CO2, subject to hitting property targets). Prices and
      CO2 factors are dynamic, so they are intentionally kept OUT of the
      training dataset and are instead read at run time from an external,
      independently-updatable data source (see price_loader.py):

          data/cost/<date>_Cost.csv   (latest file wins)
          data/co2/<date>_CO2.csv     (latest file wins)

      Call refresh_prices() to reload the latest cost/CO2 tables into
      memory (e.g. from a Streamlit button, or automatically before each
      optimisation run). No retraining is ever required when prices change
      — only the price/CO2 database needs updating.

      For backward compatibility, if no dated cost/CO2 files are found,
      this module falls back to the values baked into metadata.json at
      dataset-generation time (the original architecture).

DYNAMIC SIZING
  This module never hardcodes the synthetic or lab-batch sample counts.
  Everything it needs (materials, bounds, cost/CO2 fallbacks, dataset
  rows) is read live from data/dataset.csv and data/metadata.json, both
  of which are regenerated by generate_dataset.py from its single
  N_SYNTHETIC control constant. Changing that constant and re-running
  generate_dataset.py -> train_forward_model.py automatically flows
  through to every computation here (property ranges, cost/CO2 ranges,
  nearest-neighbour index) with no edits needed in this file.
"""

import json
import warnings
import numpy as np
import pandas as pd
from pathlib import Path

import joblib
import optuna
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

from price_loader import load_price_table

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

BASE_DIR = Path(__file__).parent
DATADIR = BASE_DIR / "data"
MODELDIR = BASE_DIR / "models"

# Dynamic price/CO2 database folders — see price_loader.py
COST_DIR = DATADIR / "cost"
CO2_DIR = DATADIR / "co2"

# ── Load dataset and model (unchanged from original architecture) ─────────────
dataset = pd.read_csv(DATADIR / "dataset.csv")
forward_model = joblib.load(MODELDIR / "forward_model.joblib")

with open(DATADIR / "metadata.json") as f:
    meta = json.load(f)

with open(MODELDIR / "feature_cols.json") as f:
    model_feature_cols: list[str] = json.load(f)

materials = meta["materials"]
bounds = meta["bounds"]

# Fallback values (original static architecture) used only if no dated
# cost/CO2 CSV files are found in data/cost/ or data/co2/.
_fallback_cost = meta.get("cost_tk_per_kg", {m: 1.0 for m in materials})
_fallback_co2_raw = meta.get("co2_kg_per_kg", {m: 0.0 for m in materials})
_fallback_co2 = {
    m: float(np.mean(v)) if isinstance(v, (list, tuple)) else float(v)
    for m, v in _fallback_co2_raw.items()
}

TARGET_COLS = ["MOR_MPa", "WA_pct", "Shrinkage_pct"]

# ── Module-level state populated by refresh_prices() ───────────────────────
cost_dict: dict[str, float] = {}
co2_dict: dict[str, float] = {}
price_info: dict = {"cost": {}, "co2": {}}

_ds_synth: pd.DataFrame = pd.DataFrame()
_pr: dict[str, float] = {}
_prop_ranges: dict[str, float] = {}
_cost_min = _cost_max = _cost_range = 0.0
_co2_min = _co2_max = _co2_range = 0.0
_prop_scaler: StandardScaler | None = None
_X_props_sc = None
_nbrs: NearestNeighbors | None = None

# ── Composition trust-region state (guards Bayesian Optimisation against
#    extrapolating off the region the forward model was actually trained
#    on — see GUARDRAIL note in the module docstring) ───────────────────
_comp_scaler: StandardScaler | None = None
_X_comp_sc = None
_comp_nbrs: NearestNeighbors | None = None
_trust_region_threshold: float = float("inf")  # calibrated in refresh_prices()

# Percentile (of "how far a point drawn from the SAME uniform sampling
# distribution used to build the synthetic dataset sits from its nearest
# training neighbour") used as the trust-region boundary. NOTE: this is
# NOT a multiple of training-to-training spacing — with a modest
# N_SYNTHETIC in a 7-D composition space, training points are naturally
# far apart from each other (curse of dimensionality / "empty space"
# phenomenon), so that self-spacing badly underestimates how far a
# typical, perfectly reasonable query point sits from its nearest
# training neighbour. Calibrating against a large empirical sample of
# points drawn from the box the optimiser actually searches avoids that
# trap and is what makes the guardrail below actually bind.
TRUST_REGION_PERCENTILE = 90.0
# How far outside the observed training property range (as a fraction of
# that range) a prediction may fall before it is treated as implausible.
PROPERTY_SANITY_MARGIN = 0.5
# Penalty weights — large enough to dominate the normal cost/CO2/target
# terms (which live on an O(1-10) scale) but capped so a single wild
# trial can't visually wreck the convergence plot.
EXTRAP_PENALTY_WEIGHT = 10.0
SANITY_PENALTY_WEIGHT = 20.0
PENALTY_CAP = 100.0

# Hard backstop, independent of the penalties above: no matter WHY the
# forward model misbehaves for a given input (numerically unstable
# architecture, extrapolation, a training/feature bug, ...), nothing
# downstream of _predict_clamped() can ever surface a value like
# "MOR = -1.6 billion MPa" again. Predictions are clamped to this many
# multiples of the observed training range beyond the observed min/max —
# generous enough to allow real extrapolation, small enough to guarantee
# a finite, physically-plausible-looking number is always shown. This is
# a display/objective-function safety net, NOT a substitute for the
# trust-region and sanity penalties above, which still do the real work
# of steering the optimiser away from unreliable regions.
PREDICTION_CLAMP_MULTIPLE = 5.0


def refresh_prices() -> None:
    """
    Reload the latest raw-material cost and CO2-factor tables from the
    dated CSV database (data/cost/, data/co2/) and recompute every value
    that is derived from them.

    IMPORTANT: this touches ONLY price/CO2-derived quantities. The
    forward_model (Composition -> Properties) and the property-based
    nearest-neighbour scaler/index are completely untouched — no
    retraining ever happens here. This is exactly the "Optimisation
    Layer reads a dynamic external database" design: today's price is
    10, tomorrow's is 20 — update the CSV and call refresh_prices();
    the optimizer immediately produces a new, economically-correct
    recommendation with zero model changes.
    """
    global cost_dict, co2_dict, price_info
    global dataset, _ds_synth
    global _pr, _prop_ranges
    global _cost_min, _cost_max, _cost_range
    global _co2_min, _co2_max, _co2_range
    global _prop_scaler, _X_props_sc, _nbrs
    global _comp_scaler, _X_comp_sc, _comp_nbrs, _trust_region_threshold

    cost_dict, cost_meta = load_price_table(
        COST_DIR, keyword="Cost", value_col="Price_Tk_per_kg",
        materials=materials, fallback=_fallback_cost,
    )
    co2_dict, co2_meta = load_price_table(
        CO2_DIR, keyword="CO2", value_col="CO2_kg_per_kg",
        materials=materials, fallback=_fallback_co2,
    )
    price_info = {"cost": cost_meta, "co2": co2_meta}

    # Recompute cost_Tk_per_kg / CO2_kg_per_kg for EVERY row in the dataset
    # (lab + synthetic) from the CURRENT price/CO2 tables. This is a cheap
    # linear recombination of each row's already-known composition — no
    # forward-model inference, no retraining.
    dataset["cost_Tk_per_kg"] = sum(
        dataset[f"{m}_wtpct"] / 100 * cost_dict[m] for m in materials
    )
    dataset["CO2_kg_per_kg"] = sum(
        dataset[f"{m}_wtpct"] / 100 * co2_dict[m] for m in materials
    )
    _ds_synth = dataset[dataset["source"] == "synthetic"]

    # ── Property ranges from synthetic rows only (unchanged logic) ────────
    _pr = {}
    for _t in TARGET_COLS:
        _pr[f"{_t}_min"] = float(_ds_synth[_t].min())
        _pr[f"{_t}_max"] = float(_ds_synth[_t].max())
    _prop_ranges = {
        t: max(_pr[f"{t}_max"] - _pr[f"{t}_min"], 1e-9)
        for t in TARGET_COLS
    }

    # ── Cost/CO2 ranges recomputed from CURRENT prices (was static before) ─
    _cost_min = float(_ds_synth["cost_Tk_per_kg"].min())
    _cost_max = float(_ds_synth["cost_Tk_per_kg"].max())
    _cost_range = max(_cost_max - _cost_min, 1e-9)

    _co2_min = float(_ds_synth["CO2_kg_per_kg"].min())
    _co2_max = float(_ds_synth["CO2_kg_per_kg"].max())
    _co2_range = max(_co2_max - _co2_min, 1e-9)

    # ── NN search fitted on synthetic rows only — property space is NOT
    #    affected by price, so this only needs to be (re)built once, but we
    #    keep it here so a full refresh always leaves everything consistent.
    if _prop_scaler is None:
        _prop_scaler = StandardScaler()
        _X_props_sc = _prop_scaler.fit_transform(_ds_synth[TARGET_COLS].values)
        _nbrs = NearestNeighbors(n_neighbors=10, algorithm="auto").fit(_X_props_sc)

    # ── Composition trust-region model (fit once — composition space is
    #    not affected by price, same reasoning as the property NN above) ──
    if _comp_scaler is None:
        comp_cols_full = [f"{m}_wtpct" for m in materials]
        _comp_scaler = StandardScaler()
        _X_comp_sc = _comp_scaler.fit_transform(_ds_synth[comp_cols_full].values)
        _comp_nbrs = NearestNeighbors(n_neighbors=1, algorithm="auto").fit(_X_comp_sc)

        # Empirical calibration (see TRUST_REGION_PERCENTILE comment above):
        # draw a large sample of compositions uniformly over the SAME box
        # the optimiser searches, using the SAME rejection-sampling scheme
        # as generate_dataset.py's _sample_comps (independent samples,
        # SodaF derived from the simplex constraint), then measure how far
        # each sits from its nearest ACTUAL training point. The threshold
        # is the chosen percentile of that distribution — i.e. "as far as
        # it's normal for a typical point in this box to be from the
        # training data", not an arbitrary fixed radius.
        free_mats = [m for m in materials if m != "SodaF"]
        lo_arr = np.array([bounds[m][0] for m in free_mats])
        hi_arr = np.array([bounds[m][1] for m in free_mats])
        soda_lo, soda_hi = bounds["SodaF"]
        n_calib = max(2000, 10 * len(_ds_synth))
        calib_rng = np.random.default_rng(123)
        calib_rows: list[list[float]] = []
        while len(calib_rows) < n_calib:
            v = calib_rng.uniform(lo_arr, hi_arr)
            s = 100.0 - v.sum()
            if soda_lo <= s <= soda_hi:
                c = dict(zip(free_mats, v))
                c["SodaF"] = s
                calib_rows.append([c[m] for m in materials])
        calib_arr = np.array(calib_rows)
        calib_sc = _comp_scaler.transform(calib_arr)
        d_calib, _ = _comp_nbrs.kneighbors(calib_sc, n_neighbors=1)
        _trust_region_threshold = float(
            np.percentile(d_calib[:, 0], TRUST_REGION_PERCENTILE)
        )
        print(f"  Composition trust-region threshold calibrated: "
              f"{_trust_region_threshold:.4f} (scaled-distance units; "
              f"{TRUST_REGION_PERCENTILE:.0f}th percentile over "
              f"{n_calib} calibration draws vs. {len(_ds_synth)} "
              "training points)")


def get_price_info() -> dict:
    """
    Return empty metadata to avoid displaying date/time on images.
    """
    return {}


# Populate all module-level state on first import so the module works
# exactly as before if nobody calls refresh_prices() explicitly.
refresh_prices()

# ── Process parameter defaults (held constant — fixed firing cycle) ───────
default_proc: dict[str, float] = {
    "dryer_temp_C": 180.0,
    "green_length_mm": 109.20,
    "green_width_mm": 54.60,
    "green_thickness_mm": 9.80,
    "green_weight_g": 98.50,
    "fired_length_mm": 98.00,
    "fired_weight_g": 95.05,
    "gas_Nm3_per_m2": 1.4115,
}

TGT_LABELS = {
    "MOR_MPa": "Firing MOR (MPa)",
    "WA_pct": "Water Absorption (%)",
    "Shrinkage_pct": "Fired Shrinkage (%)",
}
MAT_SHORT = {
    "AG98": "AG98",
    "AG22": "AG22",
    "AG23": "AG23",
    "SodaF": "Soda F.",
    "PotashF": "Potash F.",
    "Crushing": "Crushing",
    "ETP": "ETP Clay",
    "NaSil": "Na-Sil.",
}


# ── Helper functions ────────────────────────────────────────────────────────
def build_input_row(comp: dict[str, float]) -> pd.DataFrame:
    """Assemble a single-row DataFrame in the format expected by the forward model."""
    row = {f"{m}_wtpct": comp[m] for m in materials}
    row.update(default_proc)
    return pd.DataFrame([row])[model_feature_cols]


def clamp_targets(MOR: float, WA: float, SH: float) -> tuple[float, float, float]:
    """
    Clamp user-supplied target values to the synthetic dataset range.
    Values outside the calibrated range are clipped and a warning is issued.
    The clamped values are the actual targets used in all three methods.
    """
    MOR_c = float(np.clip(MOR, _pr["MOR_MPa_min"], _pr["MOR_MPa_max"]))
    WA_c = float(np.clip(WA, _pr["WA_pct_min"], _pr["WA_pct_max"]))
    SH_c = float(np.clip(SH, _pr["Shrinkage_pct_min"], _pr["Shrinkage_pct_max"]))
    if MOR != MOR_c:
        warnings.warn(f"MOR_MPa clamped: {MOR:.3f} -> {MOR_c:.3f} "
                       f"(dataset range [{_pr['MOR_MPa_min']:.3f}, {_pr['MOR_MPa_max']:.3f}])")
    if WA != WA_c:
        warnings.warn(f"WA_pct clamped: {WA:.4f} -> {WA_c:.4f} "
                       f"(dataset range [{_pr['WA_pct_min']:.4f}, {_pr['WA_pct_max']:.4f}])")
    if SH != SH_c:
        warnings.warn(f"Shrinkage_pct clamped: {SH:.3f} -> {SH_c:.3f} "
                       f"(dataset range [{_pr['Shrinkage_pct_min']:.3f}, "
                       f"{_pr['Shrinkage_pct_max']:.3f}])")
    return MOR_c, WA_c, SH_c


def _enforce_bounds(comp: dict[str, float]) -> dict[str, float]:
    """
    Project `comp` onto {sum = 100, bounds[m][0] <= x_m <= bounds[m][1]}.

    A naive "clip each material then rescale by total/100" (the original
    approach) can push a material that was clipped right at its bound
    back OUTSIDE that bound once the rescale factor is applied — e.g. if
    the clipped values sum to 95, scaling everything up by 100/95 will
    push a material sitting at its upper bound to 1.0526x that bound.
    This is exactly how a reported "SodaF = 44.85%" slipped out despite
    SodaF's bound being (37, 43): it was clipped to 43, then the rescale
    pushed it back up.

    Instead, redistribute the shortfall/excess iteratively ("water-
    filling"), each round spreading it only across materials that still
    have headroom in the needed direction, so no material ever ends the
    projection outside its own bound.
    """
    lo = {m: bounds[m][0] for m in materials}
    hi = {m: bounds[m][1] for m in materials}
    x = {m: float(np.clip(comp[m], lo[m], hi[m])) for m in materials}

    for _ in range(100):
        diff = 100.0 - sum(x.values())
        if abs(diff) < 1e-9:
            break
        if diff > 0:
            room = {m: hi[m] - x[m] for m in materials if hi[m] - x[m] > 1e-12}
        else:
            room = {m: x[m] - lo[m] for m in materials if x[m] - lo[m] > 1e-12}
        room_total = sum(room.values())
        if not room or room_total <= 1e-12:
            # Bounds themselves can't reach sum=100 (shouldn't happen with
            # this dataset's bounds, but fail safe rather than violate a
            # bound): stop here rather than push anything out of range.
            break
        for m, r in room.items():
            x[m] += diff * (r / room_total)
        # Re-clip for float safety, then loop again to redistribute any
        # residual caused by the re-clip.
        x = {m: float(np.clip(x[m], lo[m], hi[m])) for m in materials}

    return x


def _summarize(row: pd.Series) -> dict:
    """Package a dataset row into the standard result dictionary."""
    return {
        "composition_wtpct": {m: round(float(row[f"{m}_wtpct"]), 4)
                               for m in materials},
        "predicted": {
            "MOR_MPa": round(float(row["MOR_MPa"]), 3),
            "WA_pct": round(float(row["WA_pct"]), 5),
            "Shrinkage_pct": round(float(row["Shrinkage_pct"]), 3),
        },
        "cost_Tk_per_kg": round(float(row.get("cost_Tk_per_kg", 0)), 4),
        "CO2_kg_per_kg": round(float(row.get("CO2_kg_per_kg", 0)), 5),
    }


# ── Inverse design methods (unchanged logic — now reading dynamic prices) ──
def inverse_non_optimized(MOR_MPa: float, WA_pct: float,
                           Shrinkage_pct: float) -> dict:
    """
    Method 1: Nearest Neighbour (non-optimised).
    Returns the single synthetic dataset sample whose predicted properties
    are closest to the target in StandardScaler-normalised property space
    (equal weight for MOR, WA, and Shrinkage). No cost or CO2 consideration.
    """
    MOR_MPa, WA_pct, Shrinkage_pct = clamp_targets(MOR_MPa, WA_pct, Shrinkage_pct)
    q = _prop_scaler.transform([[MOR_MPa, WA_pct, Shrinkage_pct]])
    idx = _nbrs.kneighbors(q, n_neighbors=1, return_distance=False)[0][0]
    return _summarize(_ds_synth.iloc[idx])


def inverse_optimized(MOR_MPa: float, WA_pct: float,
                       Shrinkage_pct: float) -> tuple[dict, bool]:
    """
    Method 2: Nearest Neighbour (cost + CO2 optimised).
    Searches the 10 nearest neighbours in scaled property space and selects
    the composition with the lowest combined cost + CO2 percentile rank,
    using the CURRENTLY loaded price/CO2 tables (call refresh_prices() first
    to guarantee this reflects the latest prices).
    """
    MOR_MPa, WA_pct, Shrinkage_pct = clamp_targets(MOR_MPa, WA_pct, Shrinkage_pct)
    q = _prop_scaler.transform([[MOR_MPa, WA_pct, Shrinkage_pct]])
    idxs = _nbrs.kneighbors(q, n_neighbors=10, return_distance=False)[0]
    sub = _ds_synth.iloc[idxs].copy()
    sub["_score"] = (sub["cost_Tk_per_kg"].rank(pct=True)
                      + sub["CO2_kg_per_kg"].rank(pct=True))
    best_iloc = sub["_score"].idxmin()
    nn1_iloc = _ds_synth.index[idxs[0]]
    identical = (best_iloc == nn1_iloc)
    if identical:
        print("  WARNING: Methods 1 and 2 returned the same sample. "
              "The 10-nearest-neighbour neighbourhood lacks cost/CO2 "
              "diversity for this target.")
    return _summarize(_ds_synth.loc[best_iloc]), identical


def _composition_extrapolation_score(comp: dict[str, float]) -> float:
    """
    Scaled Euclidean distance from `comp` to its nearest neighbour in the
    synthetic training composition set. Compare against
    `_trust_region_threshold` (calibrated in refresh_prices() against the
    SAME box the optimiser searches — see TRUST_REGION_PERCENTILE
    comment) rather than any fixed constant: distances by themselves
    aren't meaningfully interpretable without that calibration.
    """
    x = np.array([[comp[m] for m in materials]])
    x_sc = _comp_scaler.transform(x)
    d, _ = _comp_nbrs.kneighbors(x_sc, n_neighbors=1)
    return float(d[0][0])


PROPERTY_PENALTY_WEIGHT = 5.0


def _asymmetric_property_penalty(MOR_p: float, WA_p: float, SH_p: float,
                                  MOR_t: float, WA_t: float, SH_t: float) -> float:
    """
    Eq. (3) of the manuscript — the ASYMMETRIC property-matching penalty.

        P = max(0, MOR* - MOR_hat)/r_MOR · w
          + max(0, WA_hat - WA*)/r_WA   · w
          + |S_hat - S*|/r_S            · w

    This function did not previously exist. The optimiser used a symmetric
    |predicted - target| term for all three properties, and streamlit_app.py
    told users so explicitly ("MOR, WA, and Shrinkage are all penalised
    symmetrically"). The manuscript, meanwhile, describes the penalty as
    asymmetric by design and then *interprets validation results through
    that asymmetry* — Section 3.3 explains the Bayesian batches' predicted
    WA sitting at or below target as "consistent with the one sided WA
    penalty in Eq. (3)". With a symmetric penalty in the code, that
    explanation had nothing behind it; the agreement was coincidental.

    The asymmetry is the engineering content of the objective:
      MOR is a MINIMUM specification  -> only under-achievement is penalised;
                                         exceeding the target is free.
      WA  is a MAXIMUM specification  -> only over-achievement is penalised;
                                         a denser body than asked for is free.
      Shrinkage is a DIMENSIONAL      -> both directions are penalised, since
      specification                      tiles must hit a size, not beat it.

    Restoring it changes what the optimiser returns: it can now spend its
    cost/CO2 budget on compositions that overshoot MOR or undershoot WA
    rather than being pulled back toward the target from both sides.
    """
    return (
        max(0.0, MOR_t - MOR_p) / _prop_ranges["MOR_MPa"] * PROPERTY_PENALTY_WEIGHT
        + max(0.0, WA_p - WA_t) / _prop_ranges["WA_pct"] * PROPERTY_PENALTY_WEIGHT
        + abs(SH_p - SH_t) / _prop_ranges["Shrinkage_pct"] * PROPERTY_PENALTY_WEIGHT
    )


def _property_sanity_penalty(MOR_p: float, WA_p: float, SH_p: float) -> float:
    """
    How far predicted properties fall outside the observed training
    range (each expressed as a multiple of that property's own range,
    with PROPERTY_SANITY_MARGIN of slack before any penalty starts).
    Zero when all three predictions are within the (slightly widened)
    training range; grows without bound the further a prediction
    (e.g. a blown-up extrapolation) strays from anything physically
    plausible for this dataset.
    """
    pen = 0.0
    for val, key in (
        (MOR_p, "MOR_MPa"), (WA_p, "WA_pct"), (SH_p, "Shrinkage_pct")
    ):
        lo, hi = _pr[f"{key}_min"], _pr[f"{key}_max"]
        rng = _prop_ranges[key]
        margin = rng * PROPERTY_SANITY_MARGIN
        if val < lo - margin:
            pen += (lo - margin - val) / rng
        elif val > hi + margin:
            pen += (val - hi - margin) / rng
    return pen


def _predict_clamped(comp: dict[str, float]) -> tuple[np.ndarray, np.ndarray]:
    """
    The ONLY place inverse_design.py calls forward_model.predict(). Returns
    (raw, clamped):
      raw     — the model's unmodified output, used for the sanity-penalty
                check (it needs to see how bad an input really is in order
                to steer the optimiser away from it).
      clamped — the same prediction, hard-clipped to
                [obs_min - PREDICTION_CLAMP_MULTIPLE*range,
                 obs_max + PREDICTION_CLAMP_MULTIPLE*range] for each
                property. Used for the target-matching penalty and for
                anything actually displayed to the user, so a misbehaving
                model can degrade to "an implausible but finite number"
                at worst, never a billion-scale value.
    """
    raw = np.asarray(forward_model.predict(build_input_row(comp))[0], dtype=float)
    clamped = np.empty_like(raw)
    for i, key in enumerate(TARGET_COLS):
        lo, hi = _pr[f"{key}_min"], _pr[f"{key}_max"]
        rng = _prop_ranges[key]
        clamped[i] = float(np.clip(
            raw[i],
            lo - PREDICTION_CLAMP_MULTIPLE * rng,
            hi + PREDICTION_CLAMP_MULTIPLE * rng,
        ))
    # Hard physical floor — independent of, and in addition to, the
    # trust-region/sanity penalties above. Those penalties steer the
    # OPTIMISER away from bad regions; they do not, by themselves,
    # prevent a physically-impossible value from being the one that gets
    # displayed when every trial for a given target is infeasible (the
    # "least-bad trial" fallback). No matter how the guardrails above are
    # tuned, a negative flexural strength or negative water absorption
    # can never be a real ceramic property, so these two are floored at
    # zero unconditionally. Shrinkage is left unclamped here since
    # (slight) expansion is physically possible and reported as a
    # negative value in some conventions.
    clamped[0] = max(clamped[0], 0.0)  # MOR_MPa
    clamped[1] = max(clamped[1], 0.0)  # WA_pct
    return raw, clamped


def inverse_bayesian_optimization(
    MOR_MPa_tgt: float,
    WA_tgt: float,
    Shrink_tgt: float,
    n_trials: int = 200,
) -> tuple[dict, list[float], optuna.Study]:
    """
    Method 3: Bayesian Optimisation (Optuna TPE).
    objective = norm_cost + norm_co2 + penalty, using the CURRENTLY loaded
    price/CO2 tables (call refresh_prices() first to guarantee this reflects
    the latest prices — no retraining of the forward model is ever needed).
    """
    MOR_MPa_tgt, WA_tgt, Shrink_tgt = clamp_targets(
        MOR_MPa_tgt, WA_tgt, Shrink_tgt
    )
    trial_vals: list[float] = []

    def _objective(trial: optuna.Trial) -> float:
        free_mats = [m for m in materials if m != "SodaF"]
        comp = {m: trial.suggest_float(f"c_{m}", bounds[m][0], bounds[m][1])
                for m in free_mats}

        # Simplex: SodaF derived from constraint
        soda_f = 100.0 - sum(comp.values())
        soda_lo, soda_hi = bounds["SodaF"][0], bounds["SodaF"][1]

        soda_pen = 0.0
        if soda_f < soda_lo:
            soda_pen = (soda_lo - soda_f) * 50.0
        elif soda_f > soda_hi:
            soda_pen = (soda_f - soda_hi) * 50.0
        comp["SodaF"] = float(np.clip(soda_f, soda_lo, soda_hi))

        comp = _enforce_bounds(comp)

        raw_pred, pred = _predict_clamped(comp)
        MOR_p, WA_p, SH_p = pred[0], pred[1], pred[2]

        cost = sum(comp[m] / 100 * cost_dict[m] for m in materials)
        co2 = sum(comp[m] / 100 * co2_dict[m] for m in materials)

        norm_cost = (cost - _cost_min) / _cost_range
        norm_co2 = (co2 - _co2_min) / _co2_range

        # Eq. (3): asymmetric in MOR (minimum spec) and WA (maximum spec),
        # symmetric in shrinkage (dimensional spec). Previously all three
        # terms were symmetric — see _asymmetric_property_penalty().
        penalty = _asymmetric_property_penalty(
            MOR_p, WA_p, SH_p, MOR_MPa_tgt, WA_tgt, Shrink_tgt
        ) + soda_pen

        # ── Trust-region + sanity guardrails (see module docstring) ────
        extrap_score = _composition_extrapolation_score(comp)
        extrap_overflow = max(0.0, extrap_score - _trust_region_threshold)
        extrap_overflow_norm = extrap_overflow / max(_trust_region_threshold, 1e-9)
        extrap_pen = min(extrap_overflow_norm * EXTRAP_PENALTY_WEIGHT, PENALTY_CAP)

        sanity_raw = _property_sanity_penalty(raw_pred[0], raw_pred[1], raw_pred[2])
        sanity_pen = min(sanity_raw * SANITY_PENALTY_WEIGHT, PENALTY_CAP)

        feasible = (extrap_overflow == 0.0) and (sanity_raw == 0.0)
        trial.set_user_attr("feasible", feasible)
        trial.set_user_attr("extrapolation_score", extrap_score)

        obj = norm_cost + norm_co2 + penalty + extrap_pen + sanity_pen
        trial_vals.append(obj)
        return obj

    sampler = optuna.samplers.TPESampler(seed=42)
    study = optuna.create_study(direction="minimize", sampler=sampler)
    study.optimize(_objective, n_trials=n_trials, show_progress_bar=False)

    # ── Select the final answer from FEASIBLE trials only ──────────────
    # study.best_trial alone is not safe to use here: with a fixed set of
    # penalty weights it is theoretically possible (though the weights
    # above are chosen to make it rare in practice) for an infeasible,
    # off-manifold trial to still score lowest on raw objective value
    # before the cap is reached. Filtering to feasible trials is what
    # actually guarantees the returned composition sits inside the region
    # the forward model was trained on.
    feasible_trials = [
        t for t in study.trials
        if t.value is not None and t.user_attrs.get("feasible", False)
    ]
    warning_msg = None
    if feasible_trials:
        best_trial = min(feasible_trials, key=lambda t: t.value)
    else:
        best_trial = study.best_trial
        warning_msg = (
            "Bayesian Optimisation found NO composition within the trust "
            "region of the training data for this target across "
            f"{n_trials} trials. Returning the least-bad trial found, but "
            "treat this result with caution: consider relaxing the "
            "target, increasing n_trials, or expanding the training "
            "dataset to cover this region."
        )
        warnings.warn(warning_msg)

    best = best_trial.params
    best_c = {m: best[f"c_{m}"] for m in materials if m != "SodaF"}
    best_c["SodaF"] = float(np.clip(
        100.0 - sum(best_c.values()),
        bounds["SodaF"][0], bounds["SodaF"][1]
    ))
    best_c = _enforce_bounds(best_c)

    _, pred = _predict_clamped(best_c)
    cost = sum(best_c[m] / 100 * cost_dict[m] for m in materials)
    co2 = sum(best_c[m] / 100 * co2_dict[m] for m in materials)

    n_feasible = len(feasible_trials)
    print(f"  Bayesian Optimisation: {n_feasible}/{n_trials} trials were "
          "inside the training trust region; result selected from those."
          if n_feasible else
          f"  Bayesian Optimisation: 0/{n_trials} trials were inside the "
          "training trust region — see warning above.")

    result = {
        "composition_wtpct": {m: round(best_c[m], 4) for m in materials},
        "predicted": {
            "MOR_MPa": round(float(pred[0]), 3),
            "WA_pct": round(float(pred[1]), 5),
            "Shrinkage_pct": round(float(pred[2]), 3),
        },
        "cost_Tk_per_kg": round(cost, 4),
        "CO2_kg_per_kg": round(co2, 5),
        "feasible": bool(feasible_trials),
        "n_feasible_trials": n_feasible,
        "n_trials": n_trials,
        "warning": warning_msg,
    }
    return result, trial_vals, study